# site settings
title: Observatorio anticorrupción
email: prensa@ciudadanointeligente.org
description: 'El Observatorio anticorrupción, conformado por Espacio Público y Ciudadano Iteligente, sigue el debate y el avance de las medidas propuestas por la Comisión Engel para mayor probidad y transparencia.'
baseurl: '//ciudadanointeligente.github.io/observatorio/' # the subpath of your site, e.g. /blog/
url: 'http://ciudadanointeligente.github.io/observatorio/' # the base hostname & protocol for your site
analytics: '' # google analytics tracking code
twitter_username: ciudadanoi
launched: false

# build settings
markdown: kramdown
