# site settings
title: Observatorio anticorrupción
email: prensa@ciudadanointeligente.org
description: '' # write an awesome description for your new site here
baseurl: '//ciudadanointeligente.github.io/observatorio/' # the subpath of your site, e.g. /blog/
url: 'http://yourdomain.com' # the base hostname & protocol for your site
analytics: '' # google analytics tracking code
twitter_username: ciudadanoi

# build settings
markdown: kramdown
