# site settings
title: 'DDAH - 21 Mayo 2016'
email: prensa@ciudadanointeligente.org
description: 'Del dicho al hecho edición 21 de mayo 2016'
baseurl: '//21m16.deldichoalhecho.cl/' # the subpath of your site, e.g. /blog/
url: 'http://21m16.deldichoalhecho.cl/' # the base hostname & protocol for your site
analytics: 'UA-xxxxxxxx-x' # google analytics tracking code
twitter_username: ciudadanoi
launched: false
# build settings
markdown: kramdown
